interface ImportMetaEnv {
	VITE_API_URI_LANDING_SERVICE: string;
	VITE_API_URI_COMMON_SERVICE: string;
	VITE_API_URI_FLIGHT_TICKET_SERVICE: string;
	VITE_API_URI_LISTING_SERVICE: string;
	VITE_API_AUTH_TOKEN: string;
}
